#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions        # Tutorial run functions
#------------------------------------------------------------------------------

# settings

#------------------------------------------------------------------------------

restore0Dir


runApplication blockMesh

runApplication checkMesh -allTopology -allGeometry -constant

runApplication $(getApplication)

runApplication postProcess -func yProfilesGraph -latestTime

./pGradient.sh log.simpleFoam
#------------------------------------------------------------------------------
