#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/CleanFunctions      # Tutorial clean functions
#------------------------------------------------------------------------------

foamListTimes -rm

rm -r postProcessing log.* pGrad.dat constant/polyMesh

#------------------------------------------------------------------------------
